/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sgh;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author bogda
 */
public class InformacionEmpleado extends javax.swing.JFrame {

    private String nombre, apellidos, telefono;
    private Date fecha;
    public Connection cn;
    public Statement st;

    public InformacionEmpleado(String nombre) {
        initComponents();
        conexionBD();
        this.nombre = nombre;
        mostrarEmpleado();
        System.out.println(nombre);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        labelFecha = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        labelNombre = new javax.swing.JLabel();
        labelApellidos = new javax.swing.JLabel();
        labelTelefono = new javax.swing.JLabel();
        jlabel = new javax.swing.JLabel();
        jbutton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 0, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Trabaja desde:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, -1, -1));

        labelFecha.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelFecha.setForeground(new java.awt.Color(255, 255, 255));
        labelFecha.setText("26/02/2020");
        jPanel1.add(labelFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 110, -1));

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Apellidos: ");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Teléfono:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Nombre:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        labelNombre.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelNombre.setForeground(new java.awt.Color(255, 255, 255));
        labelNombre.setText("Bogdan Valentin");
        jPanel1.add(labelNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 30, 190, -1));

        labelApellidos.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelApellidos.setForeground(new java.awt.Color(255, 255, 255));
        labelApellidos.setText("Gabor");
        jPanel1.add(labelApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 180, -1));

        labelTelefono.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        labelTelefono.setForeground(new java.awt.Color(255, 255, 255));
        labelTelefono.setText("666123123");
        jPanel1.add(labelTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 110, -1, -1));

        jlabel.setPreferredSize(new java.awt.Dimension(160, 180));
        jPanel1.add(jlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 20, 180, 180));

        jbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbuttonActionPerformed(evt);
            }
        });
        jPanel1.add(jbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, 100, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbuttonActionPerformed
        this.dispose();
    }//GEN-LAST:event_jbuttonActionPerformed

    private void mostrarEmpleado() {
        this.setSize(450, 300);
        setResizable(false);
        setTitle("Información del empleado");
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width / 2 - this.getSize().width / 2, dim.height / 2 - this.getSize().height / 2);
        jbutton.setBounds(150, 270, 70, 40);

        try {
            String sql = "select * from usuarios where nombre=\"" + nombre + "\";";
            ResultSet rss = st.executeQuery(sql);
            if (rss.next()) {
                apellidos = rss.getString("apellidos");
                telefono = rss.getString("telefono");
                fecha = rss.getDate("trabaja_desde");
                InputStream is = rss.getBinaryStream("imagen");
                BufferedImage bufImg = ImageIO.read(is);
                Image image = bufImg;
                int x = image.getWidth(this);
                int y = image.getHeight(this);
                Image nuevo = null;
                if (x > y) {
                    nuevo = image.getScaledInstance(180, 180 * y / x, Image.SCALE_DEFAULT);
                } else {
                    nuevo = image.getScaledInstance(180 * x / y, 180, Image.SCALE_DEFAULT);
                }
                jlabel.setIcon(new ImageIcon(nuevo));
                labelNombre.setText(nombre);
                labelApellidos.setText(apellidos);
                labelTelefono.setText(telefono);
                labelFecha.setText(fecha.toString());
            }
            sql = null;
            rss.close();
        } catch (Exception e) {
            e.printStackTrace();
        }

        ImageIcon iconoPrueba = new javax.swing.ImageIcon(getClass().getResource("/resources/botonVolver2.jpg"));
        Image imagenPrueba = iconoPrueba.getImage();
        Image imagenModificada = imagenPrueba.getScaledInstance(100, 40, java.awt.Image.SCALE_SMOOTH);
        ImageIcon iconoFinal2 = new ImageIcon(imagenModificada);
        jbutton.setIcon(iconoFinal2);
        jbutton.setBackground(null);
        jbutton.setContentAreaFilled(false);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        this.addWindowListener(new java.awt.event.WindowAdapter() {
            @Override
            public void windowClosing(java.awt.event.WindowEvent windowEvent) {
                dispose();
            }
        });

    }

    private void conexionBD() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            cn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sgh_bd", "root", "");
            st = cn.createStatement();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "No se pudo realizar la conexión con la base de datos.");
            e.printStackTrace();
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbutton;
    private javax.swing.JLabel jlabel;
    private javax.swing.JLabel labelApellidos;
    private javax.swing.JLabel labelFecha;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelTelefono;
    // End of variables declaration//GEN-END:variables
}
